function [  ] = DenoisingSubPlot( image,sig,dict_choise )
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here

figure;
subplot(151); imshow(image.original/255); title({image.name,'original'},'interpreter','none');
subplot(152); imshow(image.sigma(sig).Inoise/255); 
title({'noisy image',strcat('(PSNR=',num2str(image.sigma(sig).PSNRIn,'%.2f'),' db, SSIM= ',...
            num2str(image.sigma(sig).SSIMIn,'%.4f'), ' \sigma = ', ...
    int2str(image.sigma(sig).value),')')});
d=dict_choise(1);
subplot(153); imshow(image.sigma(sig).dict(d).Idenoise/255); 
title({strcat('denoised with ',strrep(image.sigma(sig).dict(d).name,'_', '\_')),...
    strcat('(PSNR=',num2str(image.sigma(sig).dict(d).PSNROut,'%.2f'),' db, SSIM= ',...
    num2str(image.sigma(sig).dict(d).SSIM,'%.4f'), ' \sigma = ', ...
    int2str(image.sigma(sig).value),')'),strcat(' nz=',...
            num2str(image.sigma(sig).dict(d).nz))});     
d=dict_choise(2);
subplot(154); imshow(image.sigma(sig).dict(d).Idenoise/255); 
title({strcat('denoised with ',strrep(image.sigma(sig).dict(d).name,'_', '\_')),...
    strcat('(PSNR=',num2str(image.sigma(sig).dict(d).PSNROut,'%.2f'),' db, SSIM= ',...
    num2str(image.sigma(sig).dict(d).SSIM,'%.4f'),' \sigma = ', ...
    int2str(image.sigma(sig).value),')'),strcat(' nz=',...
            num2str(image.sigma(sig).dict(d).nz))});     
d=dict_choise(3);
subplot(155); imshow(image.sigma(sig).dict(d).Idenoise/255); 
title({strcat('denoised with ',strrep(image.sigma(sig).dict(d).name,'_', '\_')),...
    strcat('(PSNR=',num2str(image.sigma(sig).dict(d).PSNROut,'%.2f'),' db, SSIM= ',...
    num2str(image.sigma(sig).dict(d).SSIM,'%.4f'),' \sigma = ', ...
    int2str(image.sigma(sig).value),')'),strcat(' nz=',...
            num2str(image.sigma(sig).dict(d).nz))});     



end

